feat: container credential provider support auth token
Kong/lua-resty-aws pull request #107
Opened 2024-02-26 08:44 UTC by windmgc

## Summary

This PR adds support for using authorization token in Container Credential Provider. Container Credential Provider uses two environment variables for the auth token content: `AWS_CONTAINER_AUTHORIZATION_TOKEN`(for token value)  and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`(for a file path that stores token value). See https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html. If one of the token env vars exists, the token value will be used as `Authorization` header value when requesting credential provider URI.

By adding support for auth token in Container Credential Provider, we can support the latest "Pod Identity" IAM Auth method in AWS EKS. See [How EKS Pod Identity works](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html)

Reference:
https://github.com/aws/aws-sdk-js/blob/3276faf83e32dfea637797c66a73431affe54e64/lib/credentials/remote_credentials.js#L118C3-L118C18

https://konghq.atlassian.net/browse/KAG-3424

2024-02-26 08:45 UTC, windmgc commented
Here @Tieske 

I added back the token environment variable and remove useless comments/TODOs

2024-02-27 07:32 UTC, Tieske requested changes

2024-02-27 07:32 UTC, Tieske commented on src/resty/aws/credentials/RemoteCredentials.lua
> +
you don't need the if statements here
```suggestion
  -- get auth token/file
  AuthToken = aws_config.global.AWS_CONTAINER_AUTHORIZATION_TOKEN
  AuthTokenFile = aws_config.global.AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE

```

2024-02-27 13:05 UTC, Tieske reviewed
lgtm, but needs a rebase

2024-02-27 13:25 UTC, windmgc commented
rebased

2024-02-27 20:58 UTC, Tieske commented on src/resty/aws/credentials/RemoteCredentials.lua
> +
was this lost in the rebase?

2024-02-28 05:59 UTC, windmgc commented on src/resty/aws/credentials/RemoteCredentials.lua
> +
ah yes, good catch

2024-02-28 06:15 UTC, windmgc commented on src/resty/aws/credentials/RemoteCredentials.lua
> +
updated, added back the suggestion fix

2024-02-28 09:59 UTC, Tieske approved these changes

2024-02-28 10:01 UTC, merged